// <auto-generated />
namespace TSST.Agile.Database.Configuration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserPicture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserPicture));
        
        string IMigrationMetadata.Id
        {
            get { return "201602111750099_UserPicture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
